export const siteData = {
  content: {
    brand: {
      name: "Vinícola Serra Dourada",
      location: "Pinto Bandeira, Serra Gaúcha",
    },
    hero: {
      eyebrow: "Vinhos de altitude, hospitalidade e presença premium",
      title: "Uma nova safra digital para vender rótulos, reservas e experiências.",
      description:
        "A Serra Dourada agora tem um site com impacto de marca, fotos reais, animações elegantes e estrutura pronta para apresentar catálogo, clube e experiências com muito mais força.",
      primaryCta: "Explorar catálogo",
      secondaryCta: "Agendar degustação",
      backgroundImage: "/images/hero-vineyard.jpg",
      featuredWine: {
        name: "Reserva do Horizonte 2021",
        description:
          "Blend de Cabernet Sauvignon e Merlot com 12 meses em carvalho francês, pensado para jantares longos e adegas exigentes.",
        grape: "Cabernet Sauvignon + Merlot",
        vintage: "Safra 2021",
        price: 189.9,
      },
    },
    stats: [
      { value: "22 ha", label: "Vinhedos de altitude" },
      { value: "8 rótulos", label: "Curadoria pronta para venda" },
      { value: "48h", label: "Fluxo ágil para pedidos" },
      { value: "4.9/5", label: "Média das degustações privadas" },
    ],
    highlights: [
      {
        index: "01",
        title: "Visual muito mais premium",
        description:
          "Tipografia editorial, painéis translúcidos, texturas, luz ambiente e ritmo de leitura mais sofisticado.",
      },
      {
        index: "02",
        title: "Fotos reais de vinhos e vinhedos",
        description:
          "A nova experiência usa imagens reais para transmitir qualidade e sair do aspecto genérico de portfólio.",
      },
      {
        index: "03",
        title: "Pronto para rodar local e online",
        description:
          "Em localhost o site conversa com a API Node. No Netlify, o catálogo continua funcionando e os formulários podem ser enviados online.",
      },
    ],
    story: {
      title:
        "Do terroir ao checkout, tudo conversa com a mesma sensação de exclusividade.",
      description:
        "A reformulação organiza a jornada completa: descoberta dos rótulos, prova social, agendamento da visita e fechamento do pedido. O site ganhou profundidade visual, narrativa comercial e estrutura técnica para evoluir sem retrabalho.",
      image:
        "https://commons.wikimedia.org/wiki/Special:FilePath/Justin%20Vineyard%20wine%20tasting%20room.jpg",
      points: [
        {
          title: "Narrativa de marca",
          description: "Cada seção reforça origem, terroir e ocasião de consumo.",
        },
        {
          title: "Conversão distribuída",
          description: "Há CTA de compra, reserva e clube em pontos diferentes da página.",
        },
        {
          title: "Base pronta para crescer",
          description:
            "Produtos, experiências e textos estão organizados para evoluir sem refazer a interface.",
        },
      ],
    },
    club: {
      title: "Clube mensal com prioridade nos lançamentos e relacionamento contínuo.",
      description:
        "Assinantes recebem lançamentos antes do público, vagas antecipadas para sunsets e uma régua mais forte de recompra.",
      benefits: [
        "2 ou 4 garrafas por ciclo com curadoria sazonal.",
        "Descontos exclusivos em eventos e reservas privadas.",
        "Frete preferencial e acesso antecipado a microlotes.",
        "Comunicação segmentada por estilo de vinho favorito.",
      ],
    },
    contact: {
      address: "Estrada dos Vinhedos, Km 11, Pinto Bandeira - RS",
      hours: "Quarta a domingo · 10h às 19h",
      phone: "(54) 99911-2048",
      email: "hospitalidade@serradourada.com.br",
    },
  },
  products: [
    {
      id: "reserva-do-horizonte-2021",
      name: "Reserva do Horizonte 2021",
      category: "Tinto",
      grape: "Cabernet Sauvignon + Merlot",
      vintage: 2021,
      price: 189.9,
      rating: 4.9,
      featured: 10,
      highlight: "Mais desejado",
      pairing: "carnes nobres e massas trufadas",
      description: "Estruturado, profundo e elegante, com fruta madura e final longo.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Red%20wine%20from%20hellburg%20Winery.jpg",
    },
    {
      id: "pinot-brut-rose",
      name: "Pinot Brut Rosé",
      category: "Espumante",
      grape: "Pinot Noir",
      vintage: 2023,
      price: 154.9,
      rating: 4.8,
      featured: 9,
      highlight: "Sunset favorite",
      pairing: "ostras, canapés e celebrações",
      description: "Borbulhas finas, acidez vibrante e textura cremosa para brindes memoráveis.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Wine%20bottle%20and%20glass%20on%20patio.jpg",
    },
    {
      id: "chardonnay-mineral-2024",
      name: "Chardonnay Mineral 2024",
      category: "Branco",
      grape: "Chardonnay",
      vintage: 2024,
      price: 119.9,
      rating: 4.7,
      featured: 8,
      highlight: "Novo lote",
      pairing: "peixes, queijos frescos e risotos",
      description: "Branco fresco com toque cítrico, tensão mineral e final preciso.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Muscadet%20wine%20bottle.jpg",
    },
    {
      id: "rose-jardim-2024",
      name: "Rosé Jardim 2024",
      category: "Rosé",
      grape: "Grenache",
      vintage: 2024,
      price: 98.9,
      rating: 4.6,
      featured: 7,
      highlight: "Leve e fresco",
      pairing: "tábuas, brunches e dias quentes",
      description: "Frutado, delicado e muito gastronômico, pensado para servir gelado.",
      image:
        "https://commons.wikimedia.org/wiki/Special:FilePath/Bottle%20and%20glass%20of%20Barefoot%20white%20zinfandel%20wine%2C%202012.jpg",
    },
    {
      id: "merlot-terroir-2022",
      name: "Merlot Terroir 2022",
      category: "Tinto",
      grape: "Merlot",
      vintage: 2022,
      price: 132.9,
      rating: 4.8,
      featured: 9,
      highlight: "Equilíbrio impecável",
      pairing: "cordeiro, cogumelos e queijos curados",
      description: "Corpo médio, taninos sedosos e notas de ameixa, cacau e ervas secas.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Enjoying%20a%20bottle%20of%20red%20wine%20(Unsplash).jpg",
    },
    {
      id: "sauvignon-brisa-2024",
      name: "Sauvignon Brisa 2024",
      category: "Branco",
      grape: "Sauvignon Blanc",
      vintage: 2024,
      price: 109.9,
      rating: 4.5,
      featured: 6,
      highlight: "Acidez luminosa",
      pairing: "frutos do mar e entradas cítricas",
      description: "Aromático, refrescante e muito fácil de amar em serviço por taça.",
      image:
        "https://commons.wikimedia.org/wiki/Special:FilePath/A%20hand%20pours%20white%20wine%20from%20a%20bottle%20into%20a%20glass%2C%20capturing%20the%20festive%20spirit%20of%20a%20gathering%20in%20a%20garden.jpg",
    },
    {
      id: "colecao-adega-serra",
      name: "Coleção Adega Serra",
      category: "Tinto",
      grape: "Seleção da casa",
      vintage: 2020,
      price: 248.9,
      rating: 4.9,
      featured: 10,
      highlight: "Edição limitada",
      pairing: "presentes, harmonizações premium e adegas",
      description: "Seleção especial de garrafas com perfil de guarda e estética marcante.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Assorted%20Ridge%20Vineyard%20wine%20bottles.jpg",
    },
    {
      id: "brut-blanc-de-blancs",
      name: "Brut Blanc de Blancs",
      category: "Espumante",
      grape: "Chardonnay",
      vintage: 2022,
      price: 164.9,
      rating: 4.7,
      featured: 8,
      highlight: "Festa pronta",
      pairing: "queijos macios, ceviche e aperitivos finos",
      description: "Espumante fresco, cremoso e preciso, com final seco e elegante.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Wine%20bottle%20and%20glass%20on%20patio.jpg",
    },
  ],
  experiences: [
    {
      id: "degustacao-classica",
      title: "Degustação Clássica de Altitude",
      duration: "90 min",
      availability: "Quarta a domingo",
      price: 165,
      description: "Tour guiado pela cave, prova de 5 rótulos e harmonização com tábua regional.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Enjoying%20a%20bottle%20of%20red%20wine%20(Unsplash).jpg",
    },
    {
      id: "sunset-private",
      title: "Sunset Private Terrace",
      duration: "2h",
      availability: "Sexta e sábado",
      price: 320,
      description: "Mesa reservada, espumante de boas-vindas e vista para os vinhedos ao pôr do sol.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Vineyard%20during%20sunset%20(Unsplash).jpg",
    },
    {
      id: "jantar-harmonizado",
      title: "Jantar Harmonizado na Cave",
      duration: "3h",
      availability: "Datas especiais",
      price: 520,
      description: "Menu em etapas com rótulos comentados pelo sommelier e vagas super limitadas.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Justin%20Vineyard%20wine%20tasting%20room.jpg",
    },
  ],
  testimonials: [
    {
      name: "Clara Ferraz",
      role: "Compradora B2B · Porto Alegre",
      quote: "Agora o site entrega o mesmo nível de refinamento que sentimos quando abrimos as garrafas da marca.",
    },
    {
      name: "Renato Amaral",
      role: "Sommelier convidado",
      quote: "Visual premium, navegação leve e um catálogo que finalmente valoriza os rótulos com fotos reais.",
    },
    {
      name: "Juliana Paim",
      role: "Eventos e hospitalidade",
      quote: "A jornada ficou muito mais comercial: reserva, clube e pedido convivem sem poluir a experiência.",
    },
  ],
}
